"use strict";
const assert=require("node:assert/strict"),test=require("node:test"),fs=require("node:fs"),path=require("node:path");
const read=p=>JSON.parse(fs.readFileSync(path.join(__dirname,"..",p),"utf8"));
test("v14 fixed UI Windows evidence is exact and cannot satisfy the different CPU039 gate",()=>{
 const w=read("docs/SKILL_CUTIN_READABILITY_WINDOWS_20260913.json");
 assert.equal(w.candidate_sha,"954e1c5c52d5453fc9fee9872b2d7e922f850a39");
 assert.equal(w.run.head_sha,w.candidate_sha);assert.equal(w.run.id,"34728306768");
 assert.equal(w.run.attempt,1);assert.equal(w.run.status,"completed");assert.equal(w.run.conclusion,"success");
 assert.deepEqual(w.jobs.map(j=>j.id),["103646336438","103646336560"]);
 for(const j of w.jobs){assert.equal(j.conclusion,"success");assert.equal(j.cutin_browser_log_lines.length,7);
  assert.ok(j.summary_log_lines.some(l=>l.endsWith("pass 634")));
  assert.ok(j.summary_log_lines.some(l=>l.endsWith("pass 147")));
  for(const l of j.summary_log_lines.filter(l=>/ (fail|cancelled|skipped) /.test(l)))assert.ok(l.endsWith(" 0"));}
 assert.ok(w.jobs[1].summary_log_lines.some(l=>l.endsWith("pass 79")));
 assert.equal(w.interpretation.not_cpu039_rerun_or_substitute,true);
 assert.equal(w.interpretation.production_not_run,true);assert.equal(w.interpretation.live_profile_reservations,0);
});
test("v14 delivery keeps its exact source and finite new wait without resetting closed CPU039",()=>{
 const c=read("docs/CHATGPT_REVIEW_DECISIONS.json").coordination;
 const text=fs.readFileSync(path.join(__dirname,"../docs/ASTRA_CUTIN_READABILITY_REQUEST_20260913.md"),"utf8");
 const marker="\n\nアストラ先生へ。",at=text.indexOf(marker);assert.ok(at>0);
 assert.equal(text.slice(at+2).trimEnd().length,4443);
 assert.ok(text.includes("3e6efd53-710a-45ed-9de4-05627ca5f40e"));
 const waits=[...c.completed_review_waits,c.wait_budget];
 const w=waits.find(x=>x.root_request_message_id==="3e6efd53-710a-45ed-9de4-05627ca5f40e");assert.ok(w);
 assert.equal(w.started_at_utc,"2026-09-13T00:49:56Z");assert.equal(w.expires_at_utc,"2026-09-13T02:49:56.000Z");
 assert.deepEqual(w.offset_minutes,[20,40,100]);assert.equal(w.max_automatic_checks,3);
 assert.equal(w.reset_on_candidate_revision,false);assert.equal(w.reset_on_restart_or_unrelated_message,false);
 const old=c.completed_review_waits.find(x=>x.root_request_message_id==="718d0bfa-6d26-4931-ac81-22a21542ec50");
 assert.equal(old.started_at_utc,"2026-09-12T23:14:20Z");assert.equal(old.expires_at_utc,"2026-09-13T01:14:20.000Z");
 assert.equal(old.automatic_checks,1);assert.equal(old.status,"response_received_closed");
});
test("v14 cut-in follow-up stays separate from published065 and the fixed CPU039 approval",()=>{
 const c=read("docs/CHATGPT_REVIEW_DECISIONS.json").coordination,p=c.remaining_brain_work.cutin_readability_preparation;
 assert.equal(p.request_id,"UDL-20260912-065");assert.equal(p.source_message_id,"bbb2135e-cfd1-4da8-845b-9e3d07d8b29a");
 assert.equal(p.previous_preparation.candidate_sha,"01a8735d81b005c2ee1f9b699f355f00e2f6222e");
 assert.equal(p.candidate_sha,"954e1c5c52d5453fc9fee9872b2d7e922f850a39");
 assert.equal(p.spec_version,"UDL-065-readability-v1.1");assert.equal(p.spec_snapshot_sha,"2af5d73528a35edc29f45b3be5b700f6ceaf4688");
 assert.equal(p.implementation_state,"implemented_partial");assert.equal(p.verification_state,"windows_gate_pass");
 assert.equal(p.release_state,"pages_published");assert.equal(p.publication,"PAGES_PUBLISHED");assert.equal(p.no_live_attempt_reserved,false);
 assert.equal(p.live_canary_attempts,1);assert.equal(p.live_canary_state,"ATTEMPT_FINISHED");
 assert.equal(p.live_canary_result.ok,false);assert.equal(p.live_canary_result.terminal,"PLAYING_OBSERVED");
 assert.equal(read(p.live_canary_result.report).ok,false);assert.equal(p.named_skill_followup.publication_authorized,false);
 assert.equal(p.review_id,"CHATGPT-REVIEW-20260913-040");assert.equal(p.pages_run,"34730074280");
 assert.equal(p.main_sha,p.candidate_sha);assert.equal(p.pages_sha,p.candidate_sha);
 const published=read(p.public_asset_evidence);assert.equal(published.public_preflight.ok,true);
 assert.equal(published.public_bytes.assets.length,4);assert.ok(published.public_bytes.assets.every(x=>x.candidateByteExact));
 assert.equal(p.tests.nonbrowser_pass,976);assert.equal(p.tests.chrome_pass,7);assert.equal(p.tests.edge_pass,7);
 assert.equal(p.windows_run,"34728306768");assert.ok(["IN_PROGRESS","SUCCESS","FAILURE"].includes(p.windows_status));
 assert.equal(p.scope,"Pages_only");assert.deepEqual(p.db_change_set,[]);assert.deepEqual(p.edge_change_set,[]);
 assert.ok(fs.existsSync(path.join(__dirname,"..",p.evidence)));
 assert.equal(c.preparing_next_slice.candidate_sha,"9590a4212d69185fc93df31b552d9bd870d5a9a3");
 assert.equal(c.preparing_next_slice.review_id,"CHATGPT-REVIEW-20260913-039");
});
test("v14 maps twelve additions to one canonical ledger with genuine source and nonduplicated repeats",()=>{
 const d=read("docs/BRAIN_V14_DELTA_INTAKE_20260913.json");
 const ledger=fs.readFileSync(path.join(__dirname,"../docs/PROJECT_COMMAND_CENTER.md"),"utf8");
 assert.equal(d.package,"BRAIN-UPDATE-20260913-14");assert.equal(d.records.length,12);
 assert.equal(new Set(d.records.map(r=>r.alias)).size,12);
 assert.equal(d.source.user_message_id,"bbb2135e-cfd1-4da8-845b-9e3d07d8b29a");
 assert.equal(d.source.assistant_message_id,"5339aea3-bc6b-4fb2-9467-ef8a082c0538");
 assert.equal(d.source.raw_text_sha256,"86ff50728f0cb3128642e81cb1373231c5a92c718edb6de31291ba09f62b071c");
 assert.equal(d.source.source_md_sha256,"b69a954497eb39807f8601b8ee03732e999a9f020de7cf6f9232e0622e828c79");
 assert.equal(d.source.body_characters,2445);assert.equal(d.source.response_complete,true);
 for(const r of d.records){assert.equal(r.source_message_id,d.source.user_message_id);
  for(const id of [...r.canonical_ids,...r.related_ids])assert.ok(ledger.includes("| "+id+" |"),id);
  assert.equal(r.implementation_state,"not_started");assert.equal(r.verification_state,"not_run");assert.equal(r.release_state,"not_merged");
  assert.equal(r.historical_publication_is_not_new_acceptance,true);}
 assert.deepEqual(d.priority_updates.applied_to,["UDL-20260912-065","UDL-20260907-023","UDL-20260912-062"]);
 assert.equal(d.priority_updates.reimport_repeat_increment,0);
 assert.equal(d.screenshot_details.status,"DETAILS_RECEIVED");assert.equal(d.verification.no_images_published,true);
 assert.equal(d.not_approval,true);
});
test("reward recollection requests an audit, while later direct Kurogane100 is adopted and independently verified",()=>{
 const d=read("docs/BRAIN_V14_DELTA_INTAKE_20260913.json"),c=read("docs/CHATGPT_REVIEW_DECISIONS.json").coordination;
 const reward=d.records.find(r=>r.alias==="ADD-20260913-MATCH-REWARD-RANGE-AUDIT");
 assert.equal(reward.intent_state,"verification_requested_user_recollection_not_adopted_economy_change");
 assert.equal(d.reward_audit.economy_changes_authorized,false);assert.equal(d.reward_audit.code_audit_by_commander,"LOCAL_CODE_VERIFIED");
 assert.equal(d.reward_audit.past_adoption_source_audit,"PARTIAL_ADOPTION_SOURCE_GAP");
 assert.equal(d.reward_audit.current_live_test,"NOT_RUN");
 assert.equal(d.reward_audit.local_tests.pass,26);assert.equal(d.reward_audit.local_tests.fail,0);assert.equal(d.reward_audit.local_tests.skipped,0);
 assert.equal(d.reward_audit.module_blob_at_first_implementation_base_and_candidate,"ca80916218a6b2855b946bdd14ac9a2b05730941");
 assert.ok(fs.existsSync(path.join(__dirname,"..",d.reward_audit.report_path)));
 assert.deepEqual(d.records.find(r=>r.alias==="ADD-20260913-TUTORIAL-RULES-ENTRY").canonical_ids,["UDL-20260913-068"]);
 const s=c.preparing_next_slice;
 assert.equal(s.candidate_sha,"9590a4212d69185fc93df31b552d9bd870d5a9a3");
 assert.equal(s.spec_version,"UDL-051-palette-v1.1");assert.equal(s.spec_snapshot_sha,"de0cc9e2299a8a69dd1bfbc9368cd98042ca9b9f");
 assert.equal(s.latest_user_change.adopted_value,100);
 assert.equal(s.latest_user_change.source.message_id,null,"no invented active-turn individual source ID");
 assert.equal(c.successor_goal.preparing_independent_slice.superseded_candidate.sha,"fa2789c975095792fe4219b0aea5023b9eaa58f0");
 assert.equal(c.successor_goal.preparing_independent_slice.superseded_candidate.review,"NOT_SENT");
 assert.equal(c.active_slice.state,"PAGES_PUBLISHED_LIVE_ACCEPTANCE_PARTIAL");
 assert.equal(c.successor_goal.completed_independent_slices[0].live_canary_attempts,1);
});
